project:
  type: website
  output-dir: docs

website:
  title: "Rohan Chakkadath"
  navbar:
    background: "#000000"  
    foreground: "#FFFFFF"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



